### ISSUE TITLE
Versions between python and numpy

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#511]
Is there any way to better organize the versions between python and numpy in scikit-beam. Right now we keep three python versions (27, 35, 36) and four numpy versions (1.10, 1.11, 1.12, 1.13) here. However, the travis test highly depends on conda-forge, which looks like to only maintain the latest two numpy versions. This will cause more issues as we move on.

**Comment by licode** [comment]
One PR got error because of this issue https://github.com/scikit-beam/scikit-beam/pull/510

**Comment by CJ-Wright** [comment]
This PR also got an error https://github.com/scikit-beam/scikit-beam/pull/486

**Comment by ericdill** [comment]
in the travis.yml there's this:

```yaml
matrix:
  include:
    - python: 3.6
      env: BUILD_DOCS=true RUN_TESTS=false NUMPY=1.13

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - NUMPY=1.10
  - NUMPY=1.11
  - NUMPY=1.12
  - NUMPY=1.13
```

This will instruct travis to do the outer product of ``python`` and ``env`` (so 12 builds) plus the one that is included in the matrix/include key. Depending on what you're asking for we can selectively test numpy 1.10 and numpy 1.11 with versions of python by manipulating the matrix/include directive like so:

What we could do instead is:

```yaml
matrix:
  include:
    - python: 3.6
      env: BUILD_DOCS=true RUN_TESTS=false NUMPY=1.13
    - python: 3.6
      NUMPY=1.11
    - python: 2.7
      NUMPY=1.10

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - NUMPY=1.12
  - NUMPY=1.13
```

The above travis.yml would reduce the number of builds to python * env + matrix/include = 6 + 3 = 9 builds. I'm not sure what the desired test cases are, but hopefully this makes sense and will allow you to tweak what you want to do?
